### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by dmonad** [y-crdt/y-crdt#111]
Hey @Horusiath,

So I generated a few test cases for you. I compiled the tests using lib0/encoding to a base64-encoded text file. Sorry, but that was the easiest way from JavaScript. Let me know if you want me to compile the files to binary.

I basically took all randomly-generated tests by Yjs (map, text, array) and compiled them all into a single benchmarking suite.

You can use the below node script to execute the tests. I'm attaching a few datasets in different sizes. Let me know if you want me to generate a dataset for a specific use case (e.g. text-only with max 10 generated updates).

Small dataset: https://drive.protonmail.com/urls/MEQ6KB5DMG#ZLpiAo78xZaf
Medium dataset: https://drive.protonmail.com/urls/KX0XGTYHVG#vh2BYYPkQbiN
Large dataset: https://drive.protonmail.com/urls/45E804NJQW#dbBiUwPgDYiX (405MB!)

---

If you can run these datasets, then it's pretty safe to say that Yrs can process all Yjs updates.

---

```js
import * as decoding from 'lib0/decoding'
import * as buffer from 'lib0/buffer'
import * as t from 'lib0/testing'
import * as Y from 'yjs'
import fs from 'fs'

const data = fs.readFileSync('./test-data.txt', 'utf8').split('\n')[0]
const binaryData = buffer.fromBase64(data)

const decoder = decoding.createDecoder(binaryData)

let testnumber = 0
while (decoding.hasContent(decoder)) {
  console.log('running test #' + ++testnumber)
  const updatesLen = decoding.readVarUint(decoder)
  const ydoc = new Y.Doc()
  for (let i = 0; i < updatesLen; i++) {
    const update = decoding.readVarUint8Array(decoder)
    Y.applyUpdate(ydoc, update)
  }

  const expectedText = decoding.readVarString(decoder)
  const expectedMap = decoding.readAny(decoder)
  const expectedArray = decoding.readAny(decoder)

  t.compare(expectedText, ydoc.getText('text').toString())
  t.compare(expectedMap, ydoc.getMap('map').toJSON())
  t.compare(expectedArray, ydoc.getArray('array').toJSON())
}
```

**Comment by Horusiath** [comment]
Closing this - we've added small/medium datasets to repo. Large one doesn't fit into github limits, so I'm running it separatelly. We may need to think about something for adding large file support to repo as a separate issue.
