### ISSUE TITLE
Question about usage with a remote server

### ISSUE THREAD

**Issue by terhechte** [y-crdt/y-crdt#117]
Hey! I'm trying to use ycrdt in a Rust project and I can't seem to wrap my head around how I would use it in a client server scenario.
The canonical example looks like this:

``` rs
 let doc = Doc::new();
    let mut txn = doc.transact(); // all Yrs operations happen in scope of a transaction
    let root = txn.get_text("root-type-name");
    root.push(&mut txn, "hello world"); // append text to our collaborative document

    // in order to exchange data with other documents we first need to create a state vector
    let remote_doc = Doc::new();
    let mut remote_txn = remote_doc.transact();
    let state_vector = remote_txn.state_vector().encode_v1();

    // now compute a differential update based on remote document's state vector
    let update = txn.encode_diff_v1(&StateVector::decode_v1(&state_vector));

    // both update and state vector are serializable, we can pass the over the wire
    // now apply update to a remote document
    remote_txn.apply_update(Update::decode_v1(update.as_slice()));
```

This is easy to understand, but it only works because the client part (`doc`) seems to have access to the remote document (`remote_doc`). I'm trying to replicate this behaviour using web sockets and I'm running into the following issue:

Generating the `update` requires access to the local `txn` and to the `remote_txn` in order to be generated. But there's no side where I have both of these. On the client I only have the `txn` and on the server only the `remote_txn`. So I can't generate the serialised data to send over the wire in order to update a remote document. I'd love to have a simple example of how this would work. 

I can think of two approaches to make this work, but it feels like I am overthinking this and there ought to be a simpler solution.

First,  a two-roundtrip approach, where the client asks the server for it's current state_vector, then generates the update, and then sends that back to the server. The same in the other direction. This roundtrip is quite difficult to implement though as in between this sequence of messages other messages can sneak in and have to be handled

The other approach is to have N+1 document instances on the server: One root document, and one document replicating each connected client. That allows me to generate the `update` payloads on the server, however I have the feeling that that's not how it is intended to be used.

I think a brief explanation of what a typical client / server setup should look like would be great.

Thanks!

**Comment by davidbrochart** [comment]
You may want to look at the [sync protocol](https://github.com/yjs/y-protocols/blob/master/PROTOCOL.md#sync-protocol-v1-encoding), which is basically what you mention in your "two-roundtrip approach". I think you're right about this concern: "in between this sequence of messages other messages can sneak in and have to be handled". I've been thinking about that too, but I don't have a solution.
I've been working on a Python library that implements this sync protocol over WebSocket, maybe it can make things clearer: https://github.com/davidbrochart/ypy-websocket.

**Comment by dmonad** [comment]
Thanks @davidbrochart, yeah the *sync protocol* is the way to go for initial implementation.

>  This roundtrip is quite difficult to implement though as in between this sequence of messages other messages can sneak in and have to be handled

This is all handled by the sync protocol. A sync protocol can be established between any two peers (client-server, but client-client works as well in a p2p mesh network). The sync protocol is always the same for every peer:

1. Once a connection is established, we send a state vector (sync step 1)
2. When we receive a *sync step 1* we send a *sync step 2* containing all the updates that the other peer doesn't have yet.
3. From now on, we need to send all updates that are generated from transactions. Ideally, you can simply listen to an `update` event. For now, you can listen to the `after_transaction` event and generate the incremental update from the transaction. The generated update must be send to all connected peers.
4. Whenever we receive updates from peers, we apply the updates in a fresh transaction.

Optional optimization for 3.: When a peer X sent us an update, we apply it in a transaction. The generated update must be sent to all clients EXCEPT the client that sent us the update. Yjs solves this by implementing a "origin" concept that defines where a transaction originates from. For now, you can simply don't implement this optimization and think about it later.

--- 

This sync protocol is proven to work reliably even in peer-to-peer mesh networks. All clients will eventually converge, even though we sometimes might have some redundancy.

Unless you are working on a specialized type of network, I recommend implementing the described sync protocol. It can make sense to implement the same binary protocol as y-protocols to make it easier to migrate to other server implementations.

**Comment by terhechte** [comment]
Thanks! This is really useful information, especially the documentation and the Python implementation. Somehow I must have missed that when I was searching the repository. I'll close this issue, though I do wonder if a link to the python implementation in the main readme would be helpful?

Thanks!
