### ISSUE TITLE
yffi example has invalid code

### ISSUE THREAD

**Issue by shinichy** [y-crdt/y-crdt#142]
I tried the yffi example code on https://github.com/y-crdt/y-crdt/tree/main/yffi, but I found two mistakes.

1. There are no `txt1` and `t1`. I assume they are `txt` and `txn`.

```
    YTransaction* txn = ytransaction_new(doc);
    YText* txt = ytext(txn, "name");
    
    // append text to our collaborative document
    ytext_insert(txt1, t1, 0, "hello world");
```

2. `ytext_destroy` is not available.

```
 ytext_destroy(txt);
```

**Comment by Horusiath** [comment]
Thanks for the note. Regarding pt.2: in the latest releases destroy methods are no longer required for shared types.

**Comment by Horusiath** [comment]
Fixed the README file for yffi.
