### ISSUE TITLE
Using lib0 in a server app

### ISSUE THREAD

**Issue by elnardu** [y-crdt/y-crdt#143]
Hello and thanks for a great library! I am trying to use it in my app, and I noticed that for the most part lib0 assumes that its input is safe. This makes it not ideal for server applications since malicious users can easily crash your server by sending an invalid lib0 payload. 

What are your thoughts on using more `Result` types in code?

**Comment by Horusiath** [comment]
Yes tbh. that was my intention originally, but it was postponed for some reasons. Maybe it's time to go back to it.

**Comment by Horusiath** [comment]
We've introduced Result type for decoding (encoding doesn't use it, since atm encoders accumulate serialized data into internal `Vec<u8>` anyway). It's now available as of v0.10.

**Comment by elnardu** [comment]
Oh wow! Thank you so much!
