### ISSUE TITLE
Docstring on `encode_update_v1` (etc) gives the wrong impression

### ISSUE THREAD

**Issue by reivilibre** [y-crdt/y-crdt#147]
> Encodes the document state to a binary format.

this sounds like it will encode the entire document, not just the changes. But in my testing, it seems to only encode the changes that were applied in that transaction.
(This is very fair, but I was looking for an easy 'encode document as bytes' option and this one seemed the most obvious.)

What I tried (and I think I was wrong to try):
```rust
doc.transact().encode_update_v1()
```

What seems to actually work:
```rust
doc.encode_state_as_update_v1(&StateVector::default())
```

Should it say 'Encodes the document *update* to a binary format' instead?

**Comment by Horusiath** [comment]
Thanks for the input. Changed the description in v0.10 release.
