### ISSUE TITLE
[Question] Why `doc.transact` doesn't need self as mutable?

### ISSUE THREAD

**Issue by namse** [y-crdt/y-crdt#178]
I think `doc.transact` is mutating method, so I guessed it should need self as mutable reference like `pub fn transact(&mut self) -> Transaction`. But it only needs `&self`.

Is there any reason about it?

**Comment by Horusiath** [comment]
Current behavior for transactions is unsafe (for bindings with other languages). Eventually we'll going to have 2 kinds of transactions (like `transact`/`transact_mut`) which will return a shared read-only and exclusive read-write transactions respectively. It's one of the higher priority goals for us for the upcoming months.

**Comment by namse** [comment]
Aha! I got it. Thank you for answer!
