### ISSUE TITLE
Expose RelativePosition

### ISSUE THREAD

**Issue by dnorman** [y-crdt/y-crdt#184]
Hello :) 

I'm trying to implement remote cursor presence indication, highlight ranges, and other features (using the Text data type) which require RelativePosition be exposed, serializable, and convertible to absolute positions – presumably similar to the functionality of Y.RelativePosition.

It would appear that efforts to this effect have already been started, but are as yet unfinished.

I would be happy to work on a pull request for this, but I figured I should submit an issue first to ascertain whether existing branches may be out there, if such a PR would be welcomed, and if there are any gotchas or policies I might need to be aware of.

Any thoughts?

Thank you!

**Comment by AJTJ** [comment]
I'd be happy to work on this as well!

**Comment by Horusiath** [comment]
Hi guys. We're currently working on the [cursor API](https://github.com/Horusiath/y-crdt/blob/bart/cursor/yrs/src/cursor.rs), which eventually could enable similar approach to the problem. I think it targets the points that you want to achieve here.

**Comment by dnorman** [comment]
Thank you! We'll dig into this.

Do you anticipate Cursors might be independently serializable outside of a Doc?
(ofc this would require avoidance of GC in the referenced Doc)

**Comment by Horusiath** [comment]
Relative positions have been released as part of yrs v0.16 - after talks with Kevin we decided to rename them into `StickyIndex`es (and absolute position into `Offset`s).
