### ISSUE TITLE
`NonNull` is not `Sync` and `Send`

### ISSUE THREAD

**Issue by Austaras** [y-crdt/y-crdt#194]
So `Subscription` cannot be used in multi thread enviroment. Seems like revert https://github.com/y-crdt/y-crdt/commit/9081d198be9d4064ce04cbacea8cc10ad9f9180d would fix that.

**Comment by Horusiath** [comment]
We're currently in a process of making a proper thread safe API. You should be able to see in the upcoming month.

**Comment by Austaras** [comment]
Oh, is there any public roadmap or something? I'd happy to work on it.

**Comment by Horusiath** [comment]
With the new observer API, subscriptions can now be passed and dropped across threads safely. Dropping is using atomic compare-and-swap operation combined with copy-on-write pattern over observed values - it may not be super performant over high churn of register/unregister callback calls over the same event, but it shouldn't be a problem with non-patological scenarios.

Released as part of v0.13.
