### ISSUE TITLE
Thread-safe API

### ISSUE THREAD

**Issue by Horusiath** [y-crdt/y-crdt#195]
# Motivation

Unlike Yjs, Yrs can be used in situations, when document contents are accessed concurrently from mulitple threads. Right now we don't provide API that supports rust-idomatic safety features at a type level. We're in a process of working on it atm.

We **don't** aim to give a full thread safety features (like internal use of locks and mutexes), as they may differ depending on runtime in use (eg. OS threads vs. async code) and compilation target (eg. Web Assembly). Instead we want to get the most out of Rust `Send`/`Sync` capable types at compile time and supplement them with internal mutability in (borrow/borrow_mut) in places where compile time support is not possible.

# How

Our strategy towards thread safe `Doc` access is oriented around splitting transactions between shared read-only ones and exclusive read-write transactions. Some initial thoughts on that were proposed some time ago in #69 . **tl;dr** we're going to offer two kinds of transactions:

```rust
pub struct Doc {
  store: Rc<RefCell<Store>>
}

// the same API will be introduced to BranchPtr
impl Doc {
  // try to obtain transaction lock in shared mode
  pub fn try_transact(&self) -> Result<Transaction, BorrowError> {
    let store: Ref<_> = self.store.try_borrow()?;
    Ok(Transaction(store))
  }

  // try to obtain transaction lock in exclusive mode
  pub fn try_transact_mut(&self) -> Result<TransactionMut, BorrowMutError>{
    let store: RefMut<_> = self.store.try_borrow_mut()?;
    Ok(TransactionMut::new(store))
  }

  pub fn transact(&self) -> Transaction {
    self.try_transact().expect("another read-write transaction is in progress")
  }

  pub fn transact_mut(&self) -> TransactionMut {
    self.try_transact_mut().expect("another transaction is in progress")
  }
}

// read-only transaction is just super lightweight wrapper around the store reference
pub struct Transaction<'doc>(Ref<'doc,Store>);

impl<'doc> ReadTxn for Transaction<'doc> { /* todo */ }

pub struct TransactionMut<'doc> {
  store: RefMut<'doc, Store>,
  // ... other fields
}

// TransactionMut can be used by all methods (both using readonly access to document store 
// and mutating it)
impl<'doc> ReadTxn for TransactionMut<'doc> { /* todo */ }
impl<'doc> WriteTxn for TransactionMut<'doc> { /* todo */ }

pub trait ReadTxn {
  fn store(&self) -> &Store;
}

pub trait WriteTxn {
  fn store_mut(&mut self) -> &mut Store;
}
```

This way:

1. We should be eventually capable of replacing all `UnsafeCell`s in the code base with `RefCell` used in fairly perf-wise way (no borrows on every access), providing Sync/Send capabilities out of the box when applicable.
2. We'll need to change all block-accessing methods to take transaction input as a parameter - either using `<T: ReadTxn>` if block access is used for reads or `<T: WriteTxn>` if method is mutating a block store. This approach is capable of providing a borrow checker support for Rust code. Thing is that we cannot provide the same guarantees for host languages (Ruby, Python, JS etc.), but that's the nature of these. We need to take into an account that introducing explicit transaction requirement on almost every methods may hinder usability - for this reason we're going to provide ability to start transactions at the `BranchPtr` level. This way we'll be able to create transactions even if we only have a shared type at hand (eg. `Text`, `Array`, `Map`), so we can provide method overrides for explicit and implicit transaction creation for host languages.
3. Some of the existing methods like Array iterator and snapshots operate over the concept of block slicing (and merging it on transaction commit). In result even though these methods where clearly used only for reads, they required mutating transactions anyway. This limitation existed because Yjs (and by extension Yrs) didn't have any concept for a descriptor of a slice of data within a block itself. We're going to change that by introducing a `BlockSlice` (a combination of block pointer + start index + end index), that doesn't modify document store by default, but can materialize the slicing range into split blocks if given read-write transaction.
4. Similar approach (removing unsafe cells) will be pushed towards observer implementation, making issues with Subscriptions not implementing `Sync`/`Send` (see: #194) non-existent.

**Comment by Horusiath** [comment]
Done and released as part of v0.13.

**Comment by trungleduc** [comment]
Hi, I'm having an issue while accessing a `YDoc` created from another thread. The reproduction code is in `python` but I think the error message comes from the `rust` part so I want to report here the issue. 

```python
import y_py as Y
import threading, queue
q = queue.Queue()
def create_doc(q):
    a = Y.YDoc()
    q.put(a)
thread = threading.Thread(target=create_doc, args=(q,))
thread.start()
thread.join()
doc = q.get()
doc.get_array('foo')
```
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `ThreadId(1)`,
 right: `ThreadId(4)`: y_py::y_doc::YDoc is unsendable, but sent to another thread!', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.16.6/src/impl_/pyclass.rs:853:9
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[15], line 11
      9 thread.join()
     10 doc = q.get()
---> 11 doc.get_array('foo')

PanicException: assertion failed: `(left == right)`
  left: `ThreadId(1)`,
 right: `ThreadId(4)`: y_py::y_doc::YDoc is unsendable, but sent to another thread!
```

**Comment by Horusiath** [comment]
@trungleduc this is a Python language binding issue. Would you mind posting this issue on y-py issue tracker? https://github.com/y-crdt/ypy/issues
