### ISSUE TITLE
Any reason why Into<Any> for i32 creates Number(f64)?

### ISSUE THREAD

**Issue by yrashk** [y-crdt/y-crdt#212]
I am wondering if there's a particular motivation for why `Into<Any>` for `i32` creates `Number` (which is `f64`) as opposed to `BigInt` (which is `i64`)?

**Comment by Horusiath** [comment]
It's for Yjs compatibility. `Any` type variants are directly related to lib0 encoding which is used by Yjs, which encodes all JS numbers as f64, and JS BigInt as a special case.

**Comment by yrashk** [comment]
Thank you!
