### ISSUE TITLE
Getting formats/embeds out of YText?

### ISSUE THREAD

**Issue by pontaoski** [y-crdt/y-crdt#218]
I can see APIs where you can add these to YText objects, but not how you can get them out of them. Looking at the unit tests, I only see diffs containing this information. Am I missing something?

**Comment by Horusiath** [comment]
You've seen right. The basic way to retrieve all elements (not only the string alone) is to call `Text::diff`. Are you looking for a way to get a single element/character out of text without producing a full diff?
