### ISSUE TITLE
`Doc::get_or_insert_map` not obviously the right way to create a map and not obvious that it can't be used in a transaction

### ISSUE THREAD

**Issue by reivilibre** [y-crdt/y-crdt#235]
This is *probably* a documentation issue rather than a real issue, but I thought I'd raise it here for thoughts.

Given a `Doc`, I want to insert a map and populate it with some values. (This is code for creating a new document and setting it up from scratch.)

Here's an example:

```rust
        let mut txn = new_doc.transact_mut();
        let meta_map = new_doc.get_or_insert_map("meta");
```

Already I got confused that there doesn't seem to be an equivalent of `get_or_insert_map` on `txn` — only `get_map` which returns `Option<MapRef>` and sounds like it would just return `None`.

However the code above doesn't work — I get a runtime crash/panic `tried to get a root level type while another transaction on the document is open: BorrowMutError`.

It *looks like* I have to swap the order around:
```rust
        let meta_map = new_doc.get_or_insert_map("meta");
        let mut txn = new_doc.transact_mut();
```

But even reading the documentation I don't find this obvious or convincing. (`get_or_insert_map` doesn't say it will panic if there's a transaction open, either.) I would have expected to create the map within a transaction since it *feels like* a transactional operation. Or at least it should be documented how I should have done this.

(Very possible I overlooked something that should have been obvious; sorry in that case.)

Finally; the run-time panic was unexpected, particularly since `get_or_insert_map` takes `&self` and it looks as though it could have been called concurrently from multiple threads since `Doc: Sync`.

**Comment by colelawrence** [comment]
I also had the same curiosity. There are a few interesting things with yrs that make this not the most obvious thing to "fix". Particularly that `yrs::Doc` is actually more like `yrs::DocRef` in that it doesn't uniquely own its underlying store.
Anyways, I think that there are a couple small issues surrounding transactions not being clear about when they can cause panics. I think it is up to the user-code to be careful about managing transactions.

For example, I'm working on a (currently closed source) wrapper around `yrs` which enforces some of the remaining common Rust ownership patterns you'd expect. Perhaps, once our library is open sourced, it can serve as inspiration to improve the APIs of `yrs`. I cannot directly comment on the plans for `y-crdt` as I'm just a user of the lib.

I'm really pleased by the re-write from 0.13.0 -> 0.14 where they've added MapRef and ReadTxn properly, as that was a huge leap in readability.

**Comment by Horusiath** [comment]
You're right in this regard: `Doc::get_or_insert` should indeed be communicating more in the terms of its constrains - either returning a result or just straight up change the the API signature to make use of borrow checker to not allow this method be used while a transaction has been created.

In general me and @dmonad opinion is that all root level types (the ones created straight from the document) should be defined along with the document itself at its creation. However for the compatibility with Yjs we couldn't make it this way.

**Comment by Horusiath** [comment]
While we decided to not change the behavior of the `get_or_insert_` methods, [panics are now documented](https://docs.rs/yrs/latest/yrs/struct.Doc.html#panics).
