### ISSUE TITLE
`impl fn abort(self)` on `TransactionMut`

### ISSUE THREAD

**Issue by colelawrence** [y-crdt/y-crdt#236]
I'd like to be able to `fn abort(self)` on `TransactionMut`, but I'm not entirely sure if I have the right mental model.

Does `TransactionMut::commit()` actually create a change on the Store? Or does it simply compact the changes?
If I were to `mem::forget(txn_mut)` for now, would that be the same as an `abort()` functionality?

**Comment by Horusiath** [comment]
@colelawrence Transaction changes are continuously mutating the document store as they are used. The sole purpose of committing is to compress the changes and fire lifecycle events. In a sense transactions are more like a more intelligent batches so this behaviour may be confusing, but we adopted the name from the Yjs.

There's an idea about introducing aborts but it's nowhere on the priority list and in the current architecture it will be quite a hassle to implement.

**Comment by colelawrence** [comment]
> we adopted the name from the Yjs

> the current architecture it will be quite a hassle to implement ["abort"]

@Horusiath, okay! Thanks for the clarification and context.

**Comment by Horusiath** [comment]
To conclude: we don't have plans to introduce abort on transaction atm. It's possible to use `UndoManager` to apply redo action of changes performed even across multiple transactions, however they work as compensating actions rather than reverting the state.
