### ISSUE TITLE
Any possible implications of release optimizations for binary size of `y-uniffi` bindings?

### ISSUE THREAD

**Issue by nugmanoff** [y-crdt/y-crdt#243]
Hey @Horusiath, following up on binary size thing:

I thought that it'd be better to reach out to Mozilla team directly, because they are already packaging their Rust components and consuming them from Firefox iOS & Android apps. So they should be aware and have some context.

More details: https://github.com/mozilla/uniffi-rs/issues/1448

As I said in the above issue, I did [apply](https://github.com/y-crdt/y-uniffi/blob/main/lib/Cargo.toml#L6-L11) some recommended optimizations from [min-sized-rust](https://github.com/johnthagen/min-sized-rust):

```toml
[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
```

I have seen about ~4.2x reduction in resultant static library size. Now it is around ~8MB for single architecture (ios-arm64). It is probably going to be even lower eventually, because of some optimizations that Apple do. But I need to double check that.

My question to you is basically the same, what are the implications/tradeoffs of the above optimizations? The most obvious ones I see is that all of this [opt-level](https://docs.rust-embedded.org/book/unsorted/speed-vs-size.html) thing is about space-memory tradeoff. 

But I am not sure about the rest of the configs. 

I believe that ykotlin and yswift bindings need to be quite performant as well, but if we lose some of it here and there by using UniFFI (I think all of the lifting and lowering things they do with pointers does come at a cost, but I am not sure) and sprinkling the memory optimizations on top – I wonder what we will be left with.

I think I would need to invest some time in benching all this.

**Comment by Horusiath** [comment]
From what I've seen with release of yrs crate v0.16.7 we reduced the size from 7.8MB down to 174KB. It was caused by test binary files mistakenly being included as part of the published library.
