### ISSUE TITLE
Infinite loop with subdocs

### ISSUE THREAD

**Issue by CGamesPlay** [y-crdt/y-crdt#253]
The following code exhausts the stack and crashes with yrs `0.15.0`.

```rust
#[test]
fn test_yrs_bug() {
    use yrs::{types::ToJson, Map, ReadTxn, Transact};
    let doc = yrs::Doc::new();
    let row_map = doc.get_or_insert_map("rows");
    let mut txn = doc.transact_mut();
    row_map.insert(&mut txn, String::from("key"), yrs::Doc::new());
    println!("{:?}", doc.to_json(&txn));
}
```

The problem is an infinite loop, between `Doc::to_json`, `Value::to_json`, `MapRef::to_json`, `Value::to_json` and back. I believe the problem has something to do with the subdoc attempting to print out `Transaction::root_refs`, but it passes the same transaction as the parent doc, so it is actually attempting to convert the parent doc to JSON.

I can submit a PR addressing this, but would appreciate some guidance on how to fix.

**Comment by Horusiath** [comment]
In general docs should work within their own atomic units of work and never descent recursively to subdocs. Even when used as sub-documents, `Doc` operations are expected to be isolated and execute in scope of their own transactions, not their parents (unless explicitly required).

**Comment by CGamesPlay** [comment]
Thanks for the reply. I agree with what you're saying, but I can't tell if you are suggesting that my example code is incorrect, or what the appropriate fix should be. To give some broader context of what I'm trying to do: I want to debug the Doc, to verify that its state is correct. The `Debug` implementation does not appear to provide me with useful information, and `to_json` crashes when using the library correctly (I think), so that leaves me with manually implementing a pretty-printer for the type.

What should the actual behavior be in yrs? For reference, Yjs happily converts the document to JSON using the default behavior of `JSON.stringify` notably **not** using `Y.Doc.toJSON`.

Would an acceptable fix be to have Yrs return something like `{ "$subdoc": "subdoc-guid" }`?

**Comment by Horusiath** [comment]
We could print some of the sub-docs options: formatting Doc into uuid string may be confusing - docs are supposed to be objects - but having something aligned to `{ "subdoc": { "guid": "" } }` leaves the door open for other useful fields that we may want to add in the future.

**Comment by CGamesPlay** [comment]
Thanks!
