### ISSUE TITLE
use more `Result` than `panic!` ?

### ISSUE THREAD

**Issue by darkskygit** [y-crdt/y-crdt#272]
At present, yrs will be directly panic when it process unexpected content.

In the real world, we can't always receive perfect data. Implementation errors or malicious requests from other clients will generate problematic data.

Rust has provided such a milder abstraction as `Result` that allows developers to deal with unexpected errors, and can bring the call chain, which helps to troubleshoot at runtime:

``` rust
use thiserror::Error;

#[derive(Debug, Error)]
pub enum SomeError {
    #[error("some decode error")]
    Decode(#[from] YrsError),
}

workspace.sync_decode_message(&binary)?
```

Panic will cause the current thread to crash directly for a large number of unexpected behaviors, which makes it impossible for developers to deal with errors in the same context and have to isolate all yrs calls in separate threads like this:

``` rust
    if let Err(e) = {
        use std::panic::{catch_unwind, AssertUnwindSafe};
        catch_unwind(AssertUnwindSafe(|| workspace.sync_decode_message(&binary)))
    } {
        // do something in panic
    }
```

In addition, although many functions return the result, there is still the possibility of panic. Developers can't quickly understand which functions may panic, which makes crash troubleshoot in the production environment difficult

![835231f5-2ec8-4825-8872-deb86b4a60d5](https://user-images.githubusercontent.com/25152247/222044010-e4192e2b-5465-462e-9b50-cbd29d898e0b.jpeg)

**Comment by Horusiath** [comment]
You're right - this may be a outdated part of code back from the prototyping days.

**Comment by darkskygit** [comment]
Are there any roadmaps for improvements to this problem? I am willing to submit some fix pull requests

**Comment by Horusiath** [comment]
@darkskygit PRs are welcome. I'm not sure when I can address the issue personally, it may be in the next week.

**Comment by SebastianStehle** [comment]
At the moment there are still 78 panic calls and none of them is actually a real panic in my opinion. it can just happen when you misuse the library and these kind of issues should not crash your server. So I think this has not been solved yet.

**Comment by Horusiath** [comment]
@SebastianStehle this really depends on what do you mean by missuse? 

Provide a malformed update? Sure this is an external factor and we should not panic.
Creating a new transaction within observer callback? That's not a something that's expected to happen in the wild, it's an implementation bug.

I'm going to reduce number of panics in favor of proper errors. So don't worry, things won't stay this way.

Please keep in mind, that some methods are asymmetric as they check correctness for reads but not writes (ie. `Array::get`/`Array::insert`). These are aligned with how the Rusts primitives like Vec works.

Some of the methods panic (ie. `transact`/`transact_mut`) for convenience of use, but have more elaborate way to avoid panics and use result instead (`try_transact`/`try_transact_mut`). These are also aligned with Rust (see: borrow/try_borrow).

**Comment by SebastianStehle** [comment]
If I understand it properly, I cannot handle panics at all when I integrate the library over C binding. Not sure about rust, though.

So at the moment I don't see a single panic in the code that would justify that my server crashs. lets imagine I load a doc at start time and it throws a panic due to a bug that I made and then my server does not start anymore or ends in a restart loop. Even more bad it could happen that i cannot log it anymore and I will spend hours to figure out what is going on.
