### ISSUE TITLE
Unexpected empty MapRef while remove from another MapRef

### ISSUE THREAD

**Issue by appflowy** [y-crdt/y-crdt#280]
```rust

#[cfg(test)]
mod tests {
    use lib0::any;
    use yrs::types::ToJson;
    use yrs::{Doc, Map, MapPrelim, Transact};
    #[test]
    fn test() {
        let doc = Doc::new();
        let map = doc.get_or_insert_map("map");
        let mut txn = doc.transact_mut();
        let nested = map.insert(
            &mut txn,
            "key1",
            MapPrelim::from([("inner", "inner value")]),
        );

        let value = map.remove(&mut txn, "key1").unwrap().to_ymap().unwrap();
        // Will panic
        assert!(value.get(&txn, "inner").is_some());
    }
}

```

The value doesn't contain anything while getting removed from the parent MapRef. Is this correct?

**Comment by Horusiath** [comment]
All remove methods - when executed over content that is nested shared types - delete the entire sub-branch of the document. Basically YDoc represents a tree-like structure with "root types" (generated via `doc.get_or_insert_X`) at its roots. If you remove a nested shared type, that type and all of its children are no longer accessible from the document's root.

Remove return type is not very useful if shared type is returned. In theory we could materialize it to `Any` with its values prior removal, but if one don't make use of them, it's a wasting a lot of computations.

**Comment by appflowy** [comment]
> 

Thank for response so fast. Yep. I just get the value before remove it. Would it be better if this situation is documented in the `remove` function.

**Comment by appflowy** [comment]
Should I open a PR for this? I am happy to contribute.

**Comment by Horusiath** [comment]
If you want to document this behaviour, feel free to contribute :+1:
