### ISSUE TITLE
Int always became BigInt.

### ISSUE THREAD

**Issue by IndexXuan** [y-crdt/y-crdt#314]
```main.rs
use ::lib0::serde::to_any;
use ::serde_json::{Result, Value};

fn main() {
    bigint_demo().unwrap();
}

fn bigint_demo() -> Result<()> {
    let data = r#"
        {
            "App": {
              "device": {
                "size": {
                  "width": 1440,
                  "height": 1024
                }
              }
            }
        }"#;

    // Parse the string of data into serde_json::Value.
    let v: Value = serde_json::from_str(data)?;

    // Access parts of the data by indexing with square brackets.
    println!("v is {:?}", v);

    println!("v to_any {:?}", to_any(&v).unwrap());

    Ok(())
}
```

which output:
![image](https://github.com/y-crdt/y-crdt/assets/6322673/8a3cc10a-d95e-4576-b955-872e608b1c76)

when the client-side yjs, we will have `1440n` which is weird.

**Comment by Horusiath** [comment]
Current problem is that numbers on Rust size are stored either as `f64` or `i64` (rounded up). Now the issue with `i64` is that its upper bound [doesn't have a safe implementation in on JS side](https://www.tutorialspoint.com/what-is-javascript-s-highest-integer-value-that-a-number-can-go-to-without-losing-precision).

We could actually improve things a little bit by checking if the integer surpasses (2^53-1) during serialization/deserialization. Maybe this is a good idea for improvement.

**Comment by Horusiath** [comment]
This should be fixed by now. Reopen the issue if it's not the case.
