### ISSUE TITLE
Question: Can the update ydoc_observe_updates_v1 sent to the client directly?

### ISSUE THREAD

**Issue by SebastianStehle** [y-crdt/y-crdt#330]
Hi,

I have a very simple test app with a list of chat messages. The client adds a new chat message `{ text: '...' }` to an YArray.

Then the server reacts on events and adds the same message to another document for notifications. For now there is no transformation, so it should be an equivalent object.

When I propagate change in my server there are basically two flows:

1. Updates from clients are propagated directly for now.
2. Updates from the server (my notifications) are gathered with `ydoc_observe_updates_v1`

I have 2 issues:

1. The size differs. it is 27 bytes (from client) vs 35 bytes (from server).
2. When the client receives the notification update, it throws an error from `decoder.readVarUint`. 

```
Uncaught Error: Integer out of Range
    at create3 (error.js:12:28)
    at decoding.js:38:38
```

 So I think I make something fundamentally wrong.

**Comment by Horusiath** [comment]
Are you sure, you're using the same encoding (_v1 vs _v2)? Also having a sample code would be useful.

**Comment by SebastianStehle** [comment]
Hi, 

my code is written with a C# wrapper. This is the class that manages documents:
https://github.com/SebastianStehle/ydotnet/blob/main/YDotNet.Server/DefaultDocumentManager.cs#L107

To keep my context information I use the following code to subscribe just to the next update:
https://github.com/SebastianStehle/ydotnet/blob/main/YDotNet.Server/Internal/SubscribeOnce.cs

And this is where I clone my chat message: https://github.com/SebastianStehle/ydotnet/blob/main/Demo/Callback.cs#L80

**Comment by SebastianStehle** [comment]
I also observed that when I reload my html test page it does not show the new notification. But when I restart the server it works fine. So something is off with the intermediate state.

**Comment by SebastianStehle** [comment]
I have found the problem. I realized that yjs uses 32bits for client ids and y-crdt uses 64 bits for client ids: https://github.com/y-crdt/y-crdt/blob/bb26eb73ab4ac6899ad3b6f29f9c9be281ef4a33/yffi/src/lib.rs#L247

Then the decoding fails if the ID is too large.

**Comment by Horusiath** [comment]
Strange, @dmonad was a proponent of 53bit client IDs himself. I've thought that they are supported by default in yjs by now.

**Comment by SebastianStehle** [comment]
Sure, but there is a still a wide range of numbers between (2^53 – 1) and (2^64 - )

**Comment by SebastianStehle** [comment]
Hi, it was **13.5.6**. I don't know which client id was the problem, because i have already switch to integer. But it was created in the .NET wrapper on the server side using a random generator for long. So outside of this project.

But it seems you also use 32bit by default: https://github.com/y-crdt/y-crdt/blob/bb26eb73ab4ac6899ad3b6f29f9c9be281ef4a33/yrs/src/doc.rs#L629C7-L629C40

**Comment by dmonad** [comment]
That's a very old release. Please upgrade if you want this to work.

53bit is officially supported and recommended. 32bit is also fine and used for compatibility with older releases.
