### ISSUE TITLE
to_json doesn't return valid JSON

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/y-crdt#332]
`to_json` seems to return strings without quotes, which I think is not valid JSON?
The follow prints `[hello]` instead of `["hello"]`:
```rust
let doc = Doc::new();
let array = doc.get_or_insert_array("array");
let mut txn = doc.transact_mut();
array.push_back(&mut txn, "hello");
let s = array.to_json(&txn);
println!("{s}");
```

**Comment by Horusiath** [comment]
`to_json` as found in shared collection objects returns an `Any` type, which is basically a substitution for JavaScript dynamic objects. It has it's own [to_json](https://docs.rs/lib0/0.16.10/lib0/any/enum.Any.html#method.to_json) method - call it if you want to get an actual JSON string.

**Comment by davidbrochart** [comment]
Thanks!
