### ISSUE TITLE
UndoManager: incorrect redo result

### ISSUE THREAD

**Issue by obeah** [y-crdt/y-crdt#345]
Hi,

Here is a sequence of calls that illustrates potential problem:
`
       let d = Doc::new();
        let r = d.get_or_insert_map("r");
        let mut mgr = UndoManager::with_options(&d, &r, Options::default());
        mgr.include_origin(d.client_id());

        let s1 = r.insert(
            &mut d.transact_mut_with(d.client_id()),
            "s1",
            MapPrelim::<i32>::new(),
        );
        mgr.reset();

        let mut txn = d.transact_mut_with(d.client_id());
        let a = s1.insert(&mut txn, "a", ArrayPrelim::default());
        a.insert(&mut txn, 0, "a1");
        drop(txn);
        mgr.reset();

        let mut txn = d.transact_mut_with(d.client_id());
        let b = s1.insert(&mut txn, "b", ArrayPrelim::default());
        b.insert(&mut txn, 0, "b1");
        drop(txn);
        mgr.reset();

        b.insert(&mut d.transact_mut_with(d.client_id()), 1, "b2");
        mgr.reset();

        a.insert(&mut d.transact_mut_with(d.client_id()), 1, "a3");
        mgr.reset();

        a.insert(&mut d.transact_mut_with(d.client_id()), 2, "a4");
        mgr.reset();

        a.insert(&mut d.transact_mut_with(d.client_id()), 3, "a5");
        mgr.reset();

        println!("Before undo sequence: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        mgr.undo().unwrap();
        mgr.undo().unwrap();
        mgr.undo().unwrap();
        println!("Before redo 1: {}", r.to_json(&d.transact()));
        mgr.redo().unwrap();
        println!("After redo 1: {}", r.to_json(&d.transact()));
        mgr.redo().unwrap();
        println!("After redo 2: {}", r.to_json(&d.transact()));
        mgr.redo().unwrap();
        println!("After redo 3: {}", r.to_json(&d.transact()));
        mgr.redo().unwrap();
        println!("After redo 4: {}", r.to_json(&d.transact()));
`

This produces the following results:

Before undo sequence: {s1: {a: [a1, a3, a4, a5], b: [b1, b2]}}
Before redo 1: {s1: {a: [a1], b: [b1]}}
After redo 1: {s1: {b: [b1, b2], a: [a1]}}
After redo 2: {s1: {a: [a1, a3, a4], b: [b1, b2]}}
After redo 3: {s1: {a: [a1, a3, a4], b: [b1, b2]}}
After redo 4: {s1: {a: [a1, a3, a4, a5], b: [b1, b2]}}

Problems begin with 2nd redo. It restores 2 elements of the array at once (expected that only "a3" is restored). 3rd redo doesn't change the data and then 4th redo restores "a5".

**Comment by Horusiath** [comment]
I'll take a look at it tomorrow. It would be good to verify if the same issue happens in yjs.

**Comment by obeah** [comment]
Hi,

another problem, this time with undo only. Should I create a separate issue?

Test code:

`.     let d = Doc::new();
        let r = d.get_or_insert_map("r");

        let s1 = r.insert(&mut d.transact_mut(), "s1", MapPrelim::<i32>::new());

        let mut mgr = UndoManager::with_options(&d, &r, Options::default());
        let mut txn = d.transact_mut();
        let b1 = s1.insert(&mut txn, "b1", MapPrelim::<i32>::new());
        b1.insert(&mut txn, "f1", 11);
        drop(txn);
        mgr.reset();

        s1.remove(&mut d.transact_mut(), "b1");
        mgr.reset();

        let mut txn = d.transact_mut();
        let b1 = s1.insert(&mut txn, "b1", MapPrelim::<i32>::new());
        b1.insert(&mut txn, "f1", 20);
        drop(txn);
        mgr.reset();

        println!("Before undo sequence: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        println!("After undo 1: {}", r.to_json(&d.transact()));
        println!("Can undo after undo 1 {}", mgr.can_undo());
        mgr.undo().unwrap();
        println!("After undo 2: {}", r.to_json(&d.transact()));
        println!("Can undo after undo 2 {}", mgr.can_undo());`

It prints:

Before undo sequence: {s1: {b1: {f1: 20}}}
After undo 1: {s1: {}}
Can undo after undo 1 true
After undo 2: {s1: {}}
Can undo after undo 2 false

It is expected that 2nd undo produces {s1: {b1: {f1: 11}}}

**Comment by Horusiath** [comment]
Thanks @obeah, I'll be working on it this weekend. I should be able to include fix before next release.

**Comment by Horusiath** [comment]
Update: this issue is actually two issues - I've already managed to fix them, but one of the fixes caused a regression in other parts of the codebase. It should be done this week.
