### ISSUE TITLE
Document guid in updates?

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/y-crdt#346]
I can see that the document [client_id](https://github.com/y-crdt/y-crdt/blob/b337dde99db075aa4bc62042151ab967f6f36b97/yrs/src/doc.rs#L104) is encoded in each document update, but not the document [guid](https://github.com/y-crdt/y-crdt/blob/b337dde99db075aa4bc62042151ab967f6f36b97/yrs/src/doc.rs#L110).
Any reason for that?

**Comment by Horusiath** [comment]
In general connections are managed on per-document basis, so there was no need for passing document's unique id - as connection's updates are always referring to one document at the time. Theoretically you could pass this info as part of local state in [awareness protocol](https://github.com/yjs/y-protocols).

**Comment by dmonad** [comment]
@davidbrochart As Bartosz said, this is by intention. It is up to the network protocol to associate updates with specific documents. guid is only used as a reference for subdocuments.

**Comment by davidbrochart** [comment]
I guess I'm confused as to why the `client_id` is encoded in document updates then, what is it used for?

**Comment by dmonad** [comment]
Also, client_ids are generated by random and shouldn't be reused. Nor should they be used to identify users.

**Comment by davidbrochart** [comment]
Thanks for the details.

> This is a crdt-internal feature that shouldn't leak to the outside.

You mean it shouldn't be present in document updates?

**Comment by dmonad** [comment]
It is part of the lamport timestamp and hence part of every update. However, don't forget that this is very different from what you would describe as a "client id" in the context of your application. It is a CRDT internal variable that you should not think about.

**Comment by davidbrochart** [comment]
Understood, thanks!
