### ISSUE TITLE
How to revert 'apply_update'

### ISSUE THREAD

**Issue by tsln1998** [y-crdt/y-crdt#360]
I created a websocket server in Rust, which implements the protocol defined by y-websocket. 

The clients send the diff payload to the server, and then the server uses apply_update to apply it on the Doc

For example, I have accepted client `diff_a` `diff_b` `diff_c`, but one of the clients requests to return to the state of `diff_a`, then I need to send a new `diff_d` to all clients, the content of which should be the reverse patch of `diff_b` and `diff_c`. Similar to `git revert`

How should I use `diff_b` and `diff_c` to generate `diff_d`?

**Comment by dmonad** [comment]
Can't

**Comment by davidbrochart** [comment]
What you could do is replaying updates up to `diff_a` on an empty document B, then clear the content of document A and replacing it with the content of document B?

**Comment by tsln1998** [comment]
> What you could do is replaying updates up to `diff_a` on an empty document B, then clear the content of document A and replacing it with the content of document B?

I can do this on the server side, but I can't send a new diff to the client to get them back to the state of diff_a

**Comment by tsln1998** [comment]
> Why not? It's a regular update consisting of "clear old content" and "set new content".

Oh, I understand. Just replace all YDoc instances. Good idea.
