### ISSUE TITLE
Does Yrs support ClientID rotation on updates (like Yjs)?

### ISSUE THREAD

**Issue by federico-terzi** [y-crdt/y-crdt#361]
Hi folks!

Thank you for the hard work on Yrs/Yjs! 

I'm working on a use-case that requires strong integrity guarantees, and I was thinkering with Yrs ClientIDs to understand their limitations. As far as I understand, the current implementation effectively uses 32bits random bits to define a new ClientID.

On the Yjs repository, I noticed this test that verifies that if a conflicting ClientID is detected during an update, the local ID is updated: https://github.com/yjs/yjs/blob/fe36ffd122a6f2384293098afd52d2c0025fce2a/tests/doc.tests.js#L53-L62

I tried performing the same operation on Yrs, and it doesn't seem to support this mechanism:

```rust
use yrs::{updates::decoder::Decode, Doc, Map, ReadTxn, Transact, Update};

fn main() {
    let doc1 = Doc::with_client_id(0);
    let doc2 = Doc::with_client_id(0);

    assert!(doc1.client_id() == doc2.client_id());

    let update = {
        let map = doc1.get_or_insert_map("test");
        let mut txn = doc1.transact_mut();
        map.insert(&mut txn, "key", "value");
        txn.encode_update_v1()
    };

    assert!(doc1.client_id() == doc2.client_id());

    {
        let map = doc2.get_or_insert_map("test");
        let txn = doc2.transact();
        let value = map.get(&txn, "key");
        assert!(value == None);
    }

    {
        let mut txn = doc2.transact_mut();
        let update = Update::decode_v1(&update).unwrap();
        txn.apply_update(update);
    }

    {
        let map = doc2.get_or_insert_map("test");
        let txn = doc2.transact();
        let value = map.get(&txn, "key");
        assert!(value.is_some());
    }

    assert!(doc1.client_id() != doc2.client_id()); // This fails
}
```

Should I assume that Yrs _does not_ take care of automatic ClientID rotation in these circumstances?

Ultimately, my objective would be to have a robust technique to prevent corruption from happening. Do you have any recommendations on this? On top of my mind, a possible approach would be to check the `state_vector` of every update and, before applying it, verify that `update.state_vector()["local_client_id"]` is always `<=` than `local_document.state_vector["local_client_id"]`. Does it make sense?

Keep rocking! The project is amazing :)

**Comment by Horusiath** [comment]
- My personal preference would be to stop random client ID generation on Yrs side and let users explicitly assign client IDs. Both Yrs/Yjs already allow to do so:
    - If you're using central server for exchanging updates, assigning sequential numbers to the clients can even reduce payload size (client IDs are encoded using variable integer encoding, so smaller numbers take less space).
    - The same ID could be also reused between sessions on the same client/device by storing it once at the first program start and reusing it later on.
- We moved to 53bit client IDs together with Yjs (in one of the recent versions) some time ago (Yrs had this basically from day 1), which should bring down risk of random client ID collisions.

**Comment by federico-terzi** [comment]
Thank you for the insights! That's extremely helpful
