### ISSUE TITLE
Y.rs C foreign function interface

### ISSUE THREAD

**Issue by olegkh7** [y-crdt/y-crdt#370]
Hello Dear Y.js Team,
Have 2 questions but can't find answers.
1. Is Y.rs fully compatible with Y.js concerning data types (especially TEXT) and data encoding?
2. Do you have any documentation how to compile Y.rs lib into C lib to use through C foreign function interface?
Thank you in advance

**Comment by Horusiath** [comment]
1. Yes.
2. This repository has y-ffi lib. Github Actions have pipeline definition for building a C-oriented target that's used for testing purposes: https://github.com/y-crdt/y-crdt/blob/ded889eef3ff906fff833b6fb321ac2a89d18483/.github/workflows/main.yml#L92-L124 . Another project in organisation [ydotnet](https://github.com/y-crdt/ydotnet) uses this lib as well.

**Comment by olegkh7** [comment]
Got it. Thank you for the answer!
