### ISSUE TITLE
UndoManager: incorrect undo result

### ISSUE THREAD

**Issue by obeah** [y-crdt/y-crdt#371]
Hi,

Below the code that reproduces the problem. 

`

        let d = Doc::new();

        let r = d.get_or_insert_map("r");
        let s1 = r.insert(&mut d.transact_mut(), "s1", MapPrelim::<i32>::new());
        let b1_arr = s1.insert(&mut d.transact_mut(), "b1", ArrayPrelim::default());
        let el1 = b1_arr.insert(&mut d.transact_mut(), 0, MapPrelim::<i32>::new());
        el1.insert(&mut d.transact_mut(), "f1", 8);
        el1.insert(&mut d.transact_mut(), "f2", true);
        println!("Before undo manager: {}", r.to_json(&d.transact()));

        let mut mgr = UndoManager::with_options(&d, &r, Options::default());
        let mut txn = d.transact_mut();
        let el0 = b1_arr.insert(&mut txn, 0, MapPrelim::<i32>::new());
        el0.insert(&mut txn, "f1", 8);
        el0.insert(&mut txn, "f2", false);

        el1.insert(&mut txn, "f1", 13);
        el1.remove(&mut txn, "f2");
        drop(txn);
        mgr.reset();
        println!("After txn 1: {}", r.to_json(&d.transact()));

        let mut txn = d.transact_mut();
        el1.insert(&mut txn, "f2", false);
        drop(txn);
        mgr.reset();
        println!("After txn 2: {}", r.to_json(&d.transact()));

        let mut txn = d.transact_mut();
        el1.insert(&mut txn, "f2", true);
        drop(txn);
        mgr.reset();
        println!("After txn 3: {}", r.to_json(&d.transact()));

        println!("Before undo sequence: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        println!("After undo 1: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        println!("After undo 2: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        println!("After undo 3: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();

`

This produces the following result

Before undo manager: {s1: {b1: [{f2: true, f1: 8}]}}
After txn 1: {s1: {b1: [{f1: 8, f2: false}, {f1: 13}]}}
After txn 2: {s1: {b1: [{f2: false, f1: 8}, {f2: false, f1: 13}]}}
After txn 3: {s1: {b1: [{f1: 8, f2: false}, {f1: 13, f2: true}]}}
After undo 1: {s1: {b1: [{f2: false, f1: 8}, {f2: false, f1: 13}]}}
After undo 2: {s1: {b1: [{f1: 8, f2: false}, {f1: 13}]}}
After undo 3: {s1: {b1: [{f1: 8}]}}

As you can see in the last result key "f2" is lost.

**Comment by obeah** [comment]
Hi,

We have several other test cases which all seem to have similar pattern with arrays. 

But today we have found probably something different:

`
        let d = Doc::new();
        let r = d.get_or_insert_map("r");
        let s1 = r.insert(&mut d.transact_mut(), "s1", MapPrelim::<i32>::new());
        s1.insert(&mut d.transact_mut(), "f2", "AAA");
        s1.insert(&mut d.transact_mut(), "f1", false);

        println!("Before undo manager: {}", r.to_json(&d.transact()));

        let mut mgr = UndoManager::with_options(&d, &r, Options::default());
        let mut txn = d.transact_mut();
        s1.remove(&mut txn, "f2");
        drop(txn);
        mgr.reset();
        println!("After txn 1: {}", r.to_json(&d.transact()));

        let mut txn = d.transact_mut();
        s1.insert(&mut txn, "f2", "C1");
        drop(txn);
        mgr.reset();
        println!("After txn 2: {}", r.to_json(&d.transact()));
        let mut txn = d.transact_mut();
        s1.insert(&mut txn, "f2", "C2");

        drop(txn);
        mgr.reset();
        println!("After txn 3: {}", r.to_json(&d.transact()));

        println!("Before undo sequence: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        println!("After undo 1: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        println!("After undo 2: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();
        println!("After undo 3: {}", r.to_json(&d.transact()));
        mgr.undo().unwrap();

`
Output:

Before undo manager: {s1: {f1: false, f2: AAA}}
After txn 1: {s1: {f1: false}}
After txn 2: {s1: {f2: C1, f1: false}}
After txn 3: {s1: {f2: C2, f1: false}}
Before undo sequence: {s1: {f2: C2, f1: false}}
After undo 1: {s1: {f2: C1, f1: false}}
After undo 2: {s1: {f1: false}}
After undo 3: {s1: {f1: false}}

f2: AAA not restored after 3rd undo.

**Comment by Horusiath** [comment]
Thanks for these reproduce scenarios @obeah . I'll get to them once I get an occasion.

**Comment by obeah** [comment]
Thank you @Horusiath .

It looks like some println was left in the code. I get the following messages in console:
redoing <3035814349#28> (<3035814349#31>, len: 1, parent: <3035814349#3>, origin-l: <3035814349#28>, left: <3035814349#28>, 'id-number' => [ssdfsdf])

**Comment by Horusiath** [comment]
🤦 sorry, I thought that I've checked them all. I'll make a subsequent release.
