### ISSUE TITLE
Panic while using yrs from rust code compiled to wasm

### ISSUE THREAD

**Issue by obeah** [y-crdt/y-crdt#381]
Hi,

I use yrs from rust and compile our code both to native and wasm libraries. 
While using wasm library that calls yrs I get the following error:

 panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:31:9

$console_error_panic_hook::error::h45fbf866b639370e @ d43c20fdedf36d5a1abd.wasm:0x4ad175
$console_error_panic_hook::hook_impl::h95597f1c951ec6e6 @ d43c20fdedf36d5a1abd.wasm:0x32ec44
$console_error_panic_hook::hook::h13c440a09de6938d @ d43c20fdedf36d5a1abd.wasm:0x501442
$core::ops::function::Fn::call::he436a30050e4441a @ d43c20fdedf36d5a1abd.wasm:0x4e7427
$std::panicking::rust_panic_with_hook::h85b7f6628c291e12 @ d43c20fdedf36d5a1abd.wasm:0x405d06
$std::panicking::begin_panic_handler::{{closure}}::h1e17bad04a5713a4 @ d43c20fdedf36d5a1abd.wasm:0x44da6d
$std::sys_common::backtrace::__rust_end_short_backtrace::h63adae5c31458c4b @ d43c20fdedf36d5a1abd.wasm:0x5187d8
$rust_begin_unwind @ d43c20fdedf36d5a1abd.wasm:0x4c42c8
$core::panicking::panic_fmt::hf5c4cd929d4aaa9e @ d43c20fdedf36d5a1abd.wasm:0x5011d5
$std::time::SystemTime::now::h45f421f677a8c5a8 @ d43c20fdedf36d5a1abd.wasm:0x4eb760
$<yrs::undo::Options as core::default::Default>::default::{{closure}}::hc4a527efe1c0523d @ d43c20fdedf36d5a1abd.wasm:0x3da254
$yrs::undo::UndoManager<M>::handle_after_transaction::hbf7579a79be97b4a @ d43c20fdedf36d5a1abd.wasm:0xe0b0d
$yrs::undo::UndoManager<M>::with_options::{{closure}}::hb211248afa021ad2 @ d43c20fdedf36d5a1abd.wasm:0x4af14b
$yrs::store::StoreEvents::emit_after_transaction::he18c87683ebe1a2e @ d43c20fdedf36d5a1abd.wasm:0x2f0e16
$yrs::transaction::TransactionMut::commit::hdb2e0270f853d94d @ d43c20fdedf36d5a1abd.wasm:0x9259b

Which is probably caused by call to SystemTime::now in undo.rs
`
impl Default for Options {
    fn default() -> Self {
        Options {
            capture_timeout_millis: 500,
            tracked_origins: HashSet::new(),
            capture_transaction: Rc::new(|_txn| true),
            timestamp: Rc::new(|| {
                SystemTime::now()
                    .duration_since(UNIX_EPOCH)
                    .unwrap()
                    .as_millis() as u64
            }),
        }
    }
}

`

It looks like in ywasm  timestamp is overwritten after calling Options::default():
        let mut o = yrs::undo::Options::default();
        o.timestamp = Rc::new(|| js_sys::Date::now() as u64);

I understand that it is possible to avoid calling Options::default in wasm scenario, but how the code above can work in ywasm if it calls Options::default()? 

Thank you.

**Comment by Horusiath** [comment]
This is quite strange since we have a `ywasm` test for JS wrapper in our [test suite](https://github.com/y-crdt/y-crdt/blob/main/tests-wasm/y-undo.tests.js). Therefore I assumed it was working correctly, but it seems like it may be wasm-bindgen shim.

**Comment by Horusiath** [comment]
Update on the issue - `ywasm` never call `Options::default`. For JS/WebAssembly context, they are always set up manually and the timestamp provider function is specified to one working together with current platform. See for reference: https://github.com/y-crdt/y-crdt/blob/f4309464621d719daead21bf7dcb1f4dcbd5e68e/ywasm/src/doc.rs#L67-L79
