### ISSUE TITLE
When the number of YMAP updates increases, the YMAP update operation slows down significantly

### ISSUE THREAD

**Issue by marcoyohn** [y-crdt/y-crdt#382]
ymap has 1000 item
begin:
![image](https://github.com/y-crdt/y-crdt/assets/17869233/9a9b7037-df74-40bd-a3cc-48cfb35f0834)

after ymap 10000 updates:
![image](https://github.com/y-crdt/y-crdt/assets/17869233/fe834a33-1d8b-4293-a4cf-b6a91ed1013f)

**Comment by marcoyohn** [comment]
but yjs update remains unchanged

![image](https://github.com/y-crdt/y-crdt/assets/17869233/22444982-6ba3-431f-91fb-057bd3d4730a)

**Comment by Horusiath** [comment]
Thanks @marcoyohn I'll take a look at it. Could you share your test code? Are you inserting the same entry or multiple entries? From one peer or using multiple peers?

**Comment by marcoyohn** [comment]
@Horusiath updating multiple entries, from one peer
<img width="944" alt="image" src="https://github.com/y-crdt/y-crdt/assets/17869233/b5e66ec1-f83e-4fee-8a39-f7b010eba1a8">

**Comment by marcoyohn** [comment]
@Horusiath client test code
`import { setBenchmarkResult, gen, N, benchmarkTime, logMemoryUsed, getMemUsed, runBenchmark } from './utils.js'
import * as prng from 'lib0/prng'
import * as math from 'lib0/math'
import * as t from 'lib0/testing'
import { CrdtFactory, AbstractCrdt } from './index.js' // eslint-disable-line

/**
 * @param {CrdtFactory} crdtFactory
 * @param {function(string):boolean} filter
 */
export const runBenchmarksCollabDelayDocUpdateFrequently = async (crdtFactory, filter) => {
  /**
   * Helper function to run a B1 benchmarks.
   *
   * @template T
   * @param {string} id name of the benchmark e.g. "[B1.1] Description"
   * @param {Array<T>} inputData
   * @param {function(AbstractCrdt, T, number):void} changeFunction Is called on every element in inputData
   * @param {string} docName
   */
  const benchmarkTemplate = (id, inputData, changeFunction, docName) => {
    let docUpdateSize = 0
    // https://hub-she.seewo.com/she-engine-res-hub/wopi/files/133687528128513/133687532322817
    const doc = crdtFactory.create((update, local) => {
      docUpdateSize = docUpdateSize + update.length
    }, true, 'ws://127.0.0.1:1234/ws/' + docName, docName)
    
    doc.transact( () => {
      for (let i = 0; i < inputData.length; i++) {
        changeFunction(doc, inputData[i], i)
      }
    })

    // 定时统计
    let prevDocUpdateSize =  0
    setInterval(() => {
      setBenchmarkResult(crdtFactory.getName(), `${id} (totalItemSize)`, `${doc.getItemSize()} 个`)
      setBenchmarkResult(crdtFactory.getName(), `${id} (updateSize)`, `${math.round(docUpdateSize - prevDocUpdateSize)} bytes`)
      prevDocUpdateSize = docUpdateSize;

      const startHeapUsed = 0; //getMemUsed()
      logMemoryUsed(crdtFactory.getName(), id, startHeapUsed)

      setBenchmarkResult(crdtFactory.getName(), `${id} (syncDelayTime)`, doc.getSyncDelayTime())

    }, 10000);
    
    // 定时更新
    setInterval(() => {
      let count = 0;
      let randomMod = Math.ceil(Math.random()*inputData.length)
      while(randomMod < inputData.length) {
        if(count > 0) {
          break;
        }
        count++
        changeFunction(doc, inputData[randomMod], randomMod);
        randomMod = randomMod + randomMod;
      }
    }, 16);
  }

  await runBenchmark('[CollabDelayDocUpdateFrequently] 同步延迟更新频繁场景', filter, benchmarkName => {
    const inputData = [];
    for(let i = 0; i < 1000; i++) {
      inputData.push('key_' + i);
    }
    benchmarkTemplate(
      benchmarkName,
      inputData,
      (doc, s, i) => { 
        var start = performance.now();
        doc.setMap(s, 'ClientId_' + doc.getClientId() + ':' + new Date().getTime()) 
        var end = performance.now();
        console.log('cost is', `${end - start} ms`)
      },
      'CollabDelayDocUpdateFrequently'
    ) 
  })

}
`

**Comment by marcoyohn** [comment]
@Horusiath client test code
`import { setBenchmarkResult, gen, N, benchmarkTime, logMemoryUsed, getMemUsed, runBenchmark } from './utils.js'
import * as prng from 'lib0/prng'
import * as math from 'lib0/math'
import * as t from 'lib0/testing'
import { CrdtFactory, AbstractCrdt } from './index.js' // eslint-disable-line

/**
 * @param {CrdtFactory} crdtFactory
 * @param {function(string):boolean} filter
 */
export const runBenchmarksCollabDelayDocUpdateFrequently = async (crdtFactory, filter) => {
  /**
   * Helper function to run a B1 benchmarks.
   *
   * @template T
   * @param {string} id name of the benchmark e.g. "[B1.1] Description"
   * @param {Array<T>} inputData
   * @param {function(AbstractCrdt, T, number):void} changeFunction Is called on every element in inputData
   * @param {string} docName
   */
  const benchmarkTemplate = (id, inputData, changeFunction, docName) => {
    let docUpdateSize = 0
    const doc = crdtFactory.create((update, local) => {
      docUpdateSize = docUpdateSize + update.length
    }, true, 'ws://127.0.0.1:1234/ws/' + docName, docName)
    
    doc.transact( () => {
      for (let i = 0; i < inputData.length; i++) {
        changeFunction(doc, inputData[i], i)
      }
    })

    // 定时统计
    let prevDocUpdateSize =  0
    setInterval(() => {
      setBenchmarkResult(crdtFactory.getName(), `${id} (totalItemSize)`, `${doc.getItemSize()} 个`)
      setBenchmarkResult(crdtFactory.getName(), `${id} (updateSize)`, `${math.round(docUpdateSize - prevDocUpdateSize)} bytes`)
      prevDocUpdateSize = docUpdateSize;

      const startHeapUsed = 0; //getMemUsed()
      logMemoryUsed(crdtFactory.getName(), id, startHeapUsed)

      setBenchmarkResult(crdtFactory.getName(), `${id} (syncDelayTime)`, doc.getSyncDelayTime())

    }, 10000);
    
    // 定时更新
    setInterval(() => {
      let count = 0;
      let randomMod = Math.ceil(Math.random()*inputData.length)
      while(randomMod < inputData.length) {
        if(count > 0) {
          break;
        }
        count++
        changeFunction(doc, inputData[randomMod], randomMod);
        randomMod = randomMod + randomMod;
      }
    }, 16);
  }

  await runBenchmark('[CollabDelayDocUpdateFrequently] 同步延迟更新频繁场景', filter, benchmarkName => {
    const inputData = [];
    for(let i = 0; i < 1000; i++) {
      inputData.push('key_' + i);
    }
    benchmarkTemplate(
      benchmarkName,
      inputData,
      (doc, s, i) => { 
        var start = performance.now();
        doc.setMap(s, 'ClientId_' + doc.getClientId() + ':' + new Date().getTime()) 
        var end = performance.now();
        console.log('cost is', `${end - start} ms`)
      },
      'CollabDelayDocUpdateFrequently'
    ) 
  })

}
`

**Comment by marcoyohn** [comment]
@Horusiath How's the issue going?

**Comment by Horusiath** [comment]
@marcoyohn sorry, but I'm still not there yet. I'm working on final features before rolling out the next release. I'll probably at leat investigate the issue enough to determine if this can go as part of 0.18 or as a patch release after that.

**Comment by marcoyohn** [comment]
@Horusiath , I have found the reason.

Due to missing data in the incremental updates, continuing to synchronize the subsequent update increments will result in longer update times.

The solution is to manually initiate a step 1 synchronization for the updates when missing data cases are identified.
