### ISSUE TITLE
[Crash]: Option::unwrap() on a None value

### ISSUE THREAD

**Issue by appflowy** [y-crdt/y-crdt#383]
Sometimes, the application crashes at `src/block.rs:1562:54` due to calling `Option::unwrap()` on a `None` value.  

```rust
 TypePtr::ID(id) => {
     let ptr = store.blocks.get_block(id).unwrap();
      ...
 }

```
I'm having trouble reproducing this issue and am uncertain of its cause. Do you have any thoughts on why it's happening? Also, would it be more appropriate to return an error instead of using `unwrap` directly?

**Comment by Horusiath** [comment]
Technically this could happen when we have a missing update, that the current one is dependent on. However we check if all required dependencies (updates) are on their place before calling Update::integrate, so this shouldn't be an issue. 

Also this piece of a code has been modified on main already - it no longer `.unwrap()`s, so the issue shouldn't appear.
