### ISSUE TITLE
Clarifications?

### ISSUE THREAD

**Issue by MentalGear** [y-crdt/y-crdt#389]
I'd be great if you could clarify how this differs from y-octo's attempt for a rust port.

Also it seem like y-crdt is on parity with Y.js, so can we expect future version of Y.js to be build from this rust port?

**Comment by dmonad** [comment]
You could say that y-octo is more rust-idiomatic. They also support multithreading "better" (the same data can be accessed from different threads). y-crdt focuses on being generic and supporting language bindings. It would be best for you to try out both and choose your poison ;)

> Also it seem like y-crdt is on parity with Y.js, so can we expect future version of Y.js to be build from this rust port?

At some point.. maybe. Currently, wasm has some significant drawbacks (basically undebuggable, bad error messages, significantly larger bundle size, ..). In the benchmarks, Yjs is more-or-less on-par with Ywasm: https://github.com/dmonad/crdt-benchmarks/

**Comment by Horusiath** [comment]
@dmonad @MentalGear 

> They also support multithreading "better" (the same data can be accessed from different threads)

yrs also support multithreading ;) 

The main difference is that y-octo supports subset of yjs/yrs features (needed from their authors perspective) while skipping others, using Rust-specific idioms and safe code. Atm. yrs has a lot of unsafe operations and idioms that make it easier to port to other language bindings that are not aware of Rust lifetimes anyway. We're working on gradually removing these unsafe bits.

**Comment by MentalGear** [comment]
Thanks for the explanations! This comparison could also greatly benefit new
users if you could put it into the Readme.
