### ISSUE TITLE
How to load and store documents?

### ISSUE THREAD

**Issue by SebastianStehle** [y-crdt/y-crdt#400]
Hi,

I have realized that i am not entirely sure how to load and save a document to a byte array. 

Somehow it works, but there is a bug and I am not sure. Could you do me a favor and verify these two approaches?

### Store

```
using var transaction = document.WriteTransaction();

var snapshot = transaction.Snapshot();

var bytes = transaction.StateDiffV1(snapshot);
```

### Load

```
var document = new Doc();

using (var transaction = document.WriteTransaction())
{
    transaction.ApplyV1(bytes );
}
```

I think it was more a trial and error approach. In the samples I have seen `encodeStateAsUpdateV2` was used. But this requires the GC to be turned off and I am not sure if this is in general a good idea.

**Comment by Horusiath** [comment]
@SebastianStehle I think, that for store all you need is a `doc_state = ‎ytransaction_state_diff_v1‎(txn, NULL, 0, &doc_state_len)`. This encodes the document state from the beginning of the time to current one. 2nd param in state_diff (the state_vector/snapshot) marks basically the start of the time to record updates from onward to current moment in time.
