### ISSUE TITLE
Example for how to use `observe_deep`

### ISSUE THREAD

**Issue by zswaff** [y-crdt/y-crdt#430]
I have changed a few lines from [the starter example](https://github.com/y-crdt/y-crdt/tree/main/yrs#readme) trying to use `observe_deep` based on [its documentation](https://docs.rs/yrs/latest/yrs/types/trait.DeepObservable.html#method.observe_deep). I think this code should print `"observer triggered"`, but it doesn't.

Can anyone identify the issue? Or, an easier question--is there a simple example using `observe_deep` I can start with?

Thanks!

```rust
let doc = Doc::new();
let text = doc.get_or_insert_text("name");
let mut txn = doc.transact_mut(); 
text.push(&mut txn, "Hello from yrs!");
text.format(&mut txn, 11, 3, HashMap::from([
  ("link".into(), "https://github.com/y-crdt/y-crdt".into())
]));

let remote_doc = Doc::new();

// only difference from the basic example--added `mut` and the observer
let mut remote_text = remote_doc.get_or_insert_text("name");
remote_text.observe_deep(|_txn, _events| {
    println!("observer triggered");
});

let mut remote_txn = remote_doc.transact_mut();
let state_vector = remote_txn.state_vector();
let bytes = txn.encode_diff_v1(&state_vector);
let update = Update::decode_v1(&bytes).unwrap();
remote_txn.apply_update(update);
println!("{}", remote_text.get_string(&remote_txn));
```

**Comment by Horusiath** [comment]
Observe deep is useful when you have multiple shared collections nested one into another. This way you can just observe root in order to be informed about what is happening down the line. Example:

```rust
let mut doc = Doc::new();
let root = doc.get_or_insert_map("root");
let subscription = root.observe_deep(|txn, events| {
  println!("{:#?}", events);
});
let mut txn = doc.transact_mut();

let nested = root.insert(&mut txn, "nested-map", MapPrelim::<String>::empty());
nested.insert(&mut txn, "key", "value");

drop(txn); // auto-commit, all collection events triggers only on transaction commit
```

**Comment by zswaff** [comment]
Thanks so much for the quick help. This example is awesome.

Does the observer not fire during an an update? My use case is actually only for observing updates, not local changes. Adapting the example

```rust
let doc = Doc::new();
let root = doc.get_or_insert_map("root");
let mut txn = doc.transact_mut();
root.insert(&mut txn, "key", "value");

let remote_doc = Doc::new();
let mut remote_root = remote_doc.get_or_insert_map("root");
remote_root.observe_deep(|_txn, _events| {
    println!("observer triggered");
});

let mut remote_txn = remote_doc.transact_mut();
let state_vector = remote_txn.state_vector();
let bytes = txn.encode_diff_v1(&state_vector);
let update = Update::decode_v1(&bytes).unwrap();
remote_txn.apply_update(update);
println!("{:?}", remote_root.get(&remote_txn, "key"));
drop(remote_txn);
```

One side question as well--I have been seeing

> `Events` cannot be formatted using `{:?}` because it doesn't implement `Debug`

in the past and in your example. Am I missing something?

**Comment by Horusiath** [comment]
`observe_deep` returns a subscription object, which - when dropped - will unsubscribe current callback. In your example, you're not keeping subscription around, so it's dropped instantaneously.

```rust
// bad - subscription dropped right after registering observer
remote_root.observe_deep(|_txn, _events| {
    println!("observer triggered");
});

// good - remember to keep subscription around
let subscription = remote_root.observe_deep(|_txn, _events| {
    println!("observer triggered");
});
```


> > Events cannot be formatted using {:?} because it doesn't implement Debug
>
> in the past and in your example. Am I missing something?

No, it's my bad.

**Comment by zswaff** [comment]
OK, thanks so much for all of your help debugging. This works great!
