### ISSUE TITLE
Create UndoManager without initial scope?

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/y-crdt#457]
It seems that an `UndoManager` cannot be initially created with no scope, either with [new](https://github.com/y-crdt/y-crdt/blob/99b79fa88ffe758efdbb14abd34ee19a169776f0/yrs/src/undo.rs#L79) or with [with_options](https://github.com/y-crdt/y-crdt/blob/99b79fa88ffe758efdbb14abd34ee19a169776f0/yrs/src/undo.rs#L99). Or am I missing something?

**Comment by Horusiath** [comment]
It will be released in v0.19.
