### ISSUE TITLE
Undo manager undo/redo stacks

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/y-crdt#466]
AFAIU the undo manager's `undo_stack` and `redo_stack` are not accessible in the public API, unlike in Yjs.
I have a case where I need to know if there is only one item left to undo, but I don't want to undo it. It seems that having access to the `undo_stack`'s length would be a solution.

**Comment by Horusiath** [comment]
There are [UndoManager::can_undo](https://docs.rs/yrs/latest/yrs/undo/struct.UndoManager.html#method.can_undo) and `can_redo` methods for that.

**Comment by davidbrochart** [comment]
It would only tell me if there is at least one item to undo, but I want to know if there is one and only one item to undo. That is why a more general solution would be to get access to the undo/redo stacks' length.
