### ISSUE TITLE
UndoManager in v0.19.1?

### ISSUE THREAD

**Issue by SebastianStehle** [y-crdt/y-crdt#471]
Hi,

I am trying to update the .NET version to 0.19.1. But all our undo redo tests fail, e.g. this one:

https://github.com/y-crdt/ydotnet/blob/main/Tests/YDotNet.Tests.Unit/UndoManagers/CanRedoTests.cs#L25

CanRedo returns false and therefore the assert is not successful. I know that it is not very concrete, but do you know if you have changed something fundamentally?

**Comment by davidbrochart** [comment]
FWIW I just released [pycrdt](https://github.com/jupyter-server/pycrdt) with an update to Yrs v0.19.1 and I didn't see any regression.

**Comment by SebastianStehle** [comment]
Np, it is perfectly fine. I have just fixed it on our side. I mean we are still < 1.0, therefore breaking changes are to expected.
