### ISSUE TITLE
question: How can I retrieve the string-representation of a `Y.Text` (`TextRef`) after each transaction or update?

### ISSUE THREAD

**Issue by alissa-tung** [y-crdt/y-crdt#472]
Hello, I am new to yrs. Thank you for developing this. I had write a program tries to print the contents of a text in a ydoc.
I tried to write something to listen to update but at runtime:

```thread 'tokio-runtime-worker' panicked at /Users/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yrs-0.18.8/src/doc.rs:636:14:
there's another active transaction at the moment: ExclusiveAcqFailed(BorrowMutError)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My initial goal is to have an websocket server for ydoc, and when the ydoc's text change, the server print the full document. I am not sure which API should I use. I have noticed that there are:

- [observe_update_v2](https://docs.rs/yrs/latest/yrs/doc/struct.Doc.html#method.observe_update_v2)
-  observe_after_transaction
- TextRef::observe
- ....

I am not sure how to use the APIs yet. and as for the yjs version there is an `ytext.toString(): string`. Any help would be very greatly appreciated.

**Comment by Horusiath** [comment]
In yrs transactions work essentially like read-write locks. Another thing is that all of the observers are triggered when the write transaction commits or get dropped. You cannot create a new transaction inside of the observer callback, but every callback comes with a transaction that's one of its parameters.

If you want to print out the string from TextRef, you can do it using [TextRef::get_string](https://docs.rs/yrs/latest/yrs/types/text/struct.TextRef.html#method.get_string). 

```rust
let doc = Doc::with_client_id(1);
let txt = doc.get_or_insert_text("text");

let txt2 = txt.clone();
let subscription = txt.observe(move |txn, e| {
  let str = txt2.get_string(txn);
  println!("{}", str);
});

txt.insert(&mut doc.transact_mut(), 0, "c");
txt.insert(&mut doc.transact_mut(), 0, "b");
txt.insert(&mut doc.transact_mut(), 0, "a");
```

You can also take a look at the examples in [docs.rs](https://docs.rs/yrs/latest/yrs/index.html) or checkout the source code with tests.

**Comment by alissa-tung** [comment]
Thank you a lot!
