### ISSUE TITLE
Iterator over names in a Doc

### ISSUE THREAD

**Issue by Aceeri** [y-crdt/y-crdt#515]
I'm unsure if I'm missing something, but I haven't found a way to iterate over the stored contents of a document. Is there any way to do this?

Basically to expose the keys of this: https://docs.rs/yrs/latest/src/yrs/store.rs.html#37

**Comment by Horusiath** [comment]
You can use https://docs.rs/yrs/latest/yrs/trait.ReadTxn.html#method.root_refs

**Comment by Aceeri** [comment]
> You can use `doc.transact().root_refs()`: [docs.rs/yrs/latest/yrs/trait.ReadTxn.html#method.root_refs](https://docs.rs/yrs/latest/yrs/trait.ReadTxn.html#method.root_refs)

Thank you!
