### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by davidbrochart** [y-crdt/y-crdt#66]
The [PyPI package](https://pypi.org/project/y-py) currently consists of the 0.1.3 release, and wheels are provided only for Linux and Python 3.8 and 3.10:
- `y_py-0.1.3-cp310-cp310-manylinux_2_24_x86_64.whl`
- `y_py-0.1.3-cp38-cp38-manylinux_2_24_x86_64.whl`

It should be possible to release for MacOS and Windows, and also for Python 3.7 and 3.9, just by filling the matrix:
https://github.com/yjs/y-crdt/blob/4b49eea4fc3e3ae5ec87f2234149df686e430b23/.github/workflows/main.yml#L12-L14
See also #65.

**Comment by SylvainCorlay** [comment]
Should we close this issue since we are now using your github action?

**Comment by Horusiath** [comment]
Closing this one - y-py has it's own repository now: https://github.com/y-crdt/ypy
