### ISSUE TITLE
Infinite Loop in Update::merge_updates

### ISSUE THREAD

**Issue by GarettCooper** [y-crdt/y-crdt#77]
Hi, I've found a relatively simple to reproduce issue with the loop in the [merge_updates ](https://github.com/y-crdt/y-crdt/blob/89ca7502eef4e3edc54351216c145b03f5118903/yrs/src/update.rs#L470) function. I am able to consistently reproduce the issue  by repeatedly appending single characters to the end of a text document, where each character is added in its own transaction and that transaction is encoded as an update. When rebuilding the document from the encoded updates, `Update::merge_updates` gets stuck in an infinite loop until running out of memory.

Here's a CSV with hex encoded updates illustrating the issue:
[text_updates.csv](https://github.com/y-crdt/y-crdt/files/7919715/text_updates.csv)

Please let me know if any more details are required. I might take some time to try and figure this out myself but I figured it was better to share it first.

**Comment by Horusiath** [comment]
Thanks @GarettCooper, I'll take a look at it.

**Comment by Horusiath** [comment]
While I've found a bug thanks to the example provided by the CSV file, it didn't cause infinite loop. The problem was rather a clock diff calculation which could go into negative number, which caused panic since clocks themselves are `u32`.

**Comment by GarettCooper** [comment]
Ah, the dangers of running in release mode with silent overflow.

**Comment by Horusiath** [comment]
Fixed. Closing the issue.
