### ISSUE TITLE
[Pacckaging] include option to not vendor yrs in ypy

### ISSUE THREAD

**Issue by SylvainCorlay** [y-crdt/y-crdt#80]
The policy in conda-forge and for most linux distributions is to forbid Python packages to vendor binary dependencies that could be packaged independently.

A good exemple on how to do that is `pyzmq` which does bundle zeromq on PyPI but for which the conda-forge package depends on the `zeromq` conda-forge package. At build time, the building and vendoring of zeromq is disabled by specifying the installation prefix of zeromq through the `ZMQ_PREFIX` environment variable.

We will need to do the same for the case of pyrs.

**Comment by Horusiath** [comment]
The discussion on that is still ongoing on weekly y-py meetings (I think). However now, y-py exists in its own repo: https://github.com/y-crdt/ypy . I'm closing this issue here.
